### ISSUE TITLE
time for a release ?

### ISSUE THREAD

**Issue by simonmichael** [joelburget/easytest#1]
Thanks for easytest!

I haven't figured out if I should/exactly how to use it in projects just yet, and I can depend on the github repo if using stack, but a hackage release would be more convenient. Any thoughts of doing that soon ?

**Comment by simonmichael** [comment]
PS unrelated and minor feedback: the runtests executable sounded like it might be a general test finder/runner - should it be renamed easytest-demo or not installed by default or something ?

**Comment by joelburget** [comment]
Thanks for the push! In the next couple days I'll make sure the documentation looks alright and address the runtests issue you mentioned. Hopefully we'll have a release this week.

**Comment by joelburget** [comment]
I just uploaded a [candidate release](https://hackage.haskell.org/package/easytest-0.1/candidate). I'd appreciate feedback on it so I can upload a final package.

**Comment by simonmichael** [comment]
Just tested with GHC 8.2. Looks good. runtests I mentioned previously. A changelog is always nice to have, even if there's not much news yet. A stack.yaml would make building the latest source easier for stack users, eg:
```
resolver: lts-10.7
packages:
- .
```
I think you're duplicating the intro/example in cabal file, readme and haddocks. Exposing the readme on hackage would remove one of these (but perhaps doesn't look as good).

**Comment by simonmichael** [comment]
In haddock -> "For tests that are logically separate, we usually combine them into a suite...", the `<|>` is getting rendered by haddock as `|`

**Comment by simonmichael** [comment]
Possibly similar escaping issue at "If our list reversal test failed...", generating a broken hyperlink.

**Comment by simonmichael** [comment]
PS I've only written a couple of little tests so far, but.. this is what I expected unit testing would look like when I started with Haskell. Loving the simplicity and practicality!

**Comment by joelburget** [comment]
> Loving the simplicity and practicality!

Paul gets all the credit for this 🙂

I re-uploaded the package candidate with the latest and will aim to release as soon as today.

**Comment by joelburget** [comment]
> I think you're duplicating the intro/example

I'm going to leave it that way for now, but will think about changing in the future.

I just published [version 0.1 to hackage](http://hackage.haskell.org/package/easytest-0.1) 🎉

**Comment by simonmichael** [comment]
Thanks!
