### ISSUE TITLE
Question about the relation to unisonweb/unison/yaks/easytest

### ISSUE THREAD

**Issue by aniketd** [joelburget/easytest#29]
Hi folks, I really like the API of this library, so want to give kudos to you all for caring to make things easy.

I came to this repository by following the link from the package at `hackage`, but I reached `hackage` to search for whether https://github.com/unisonweb/unison/tree/trunk/yaks/easytest has been published in the first place. And, I reached the `unisonweb`'s repository by following links to the `searx` search results for "The best testing framework for Haskell" (somehow :P)

The difference I see between the two, is that the one under `unisonweb`'s repo does not use `hedgehog`. I may be complete wrong though.

I found it a bit confusing to trace whether efforts are now being made here in one place, or whether there are indeed two different projects and whether this project is supposed to be the more mainstream of the two, independently.

I thought, it would be great if the `README` mentioned the other repository to make this clear, as two which of the two one should be using and why this one uses `hedgehog` vs the other that does not. I'm only requesting this as mostly library author teams are generally more knowledgeable than the library users about the domain, and these explanations will help the latter kind be informed to make their choices.

**Comment by joelburget** [comment]
Hi Aniket, this library was originally extracted from Unison and modified to use hedgehog. I'm no longer maintaining it and I don't recommend using it.
